apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameTemplates }}-service
spec:
  selector:
    app: {{ .Values.chartLabel }}-{{ .Chart.Version }}
  ports:
    - port: {{ .Values.externalPort }}
      targetPort: {{ .Values.targetPort }}
