apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-nginx-depl
  labels:
    app: init-nginx
spec:
  selector:
    matchLabels:
      app: init-nginx
  template:
    metadata:
      labels:
        app: init-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      initContainers:
      - name: init-svc
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup init-nginx-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for init-nginx-svc; sleep 2; done"]
